#!/usr/bin/env python3
"""
make_placeholder.py — generate a SYNTHETIC embedding.json

This exists so the site is deployable before the real export lands. The output
is clearly labelled as simulated in `meta.caption`, which the page renders as
the figure legend — a scientist's site must never show fabricated data that
could be mistaken for a result.

Replace it as soon as you have real coordinates:

    Rscript tools/export_embedding.R --input seurat.rds --labels guide,Phase ...

Usage:
    python3 tools/make_placeholder.py [--output assets/data/embedding.json]
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random

SEED = 20260914
N = 6000

# Six transcriptional states, positioned in a 3-D PC space.
STATES = [
    # name,                (pc1,  pc2,  pc3), spread, n_weight
    ("Epithelial-like",    (-2.3,  1.6,  0.4), 0.95, 0.22),
    ("Mesenchymal-like",   ( 2.6,  1.1, -0.6), 1.05, 0.19),
    ("Proliferative",      ( 0.4, -2.5,  1.2), 0.80, 0.18),
    ("Interferon-response",(-1.4, -1.9, -1.5), 0.70, 0.14),
    ("Stress / hypoxic",   ( 2.1, -1.4,  1.6), 0.85, 0.15),
    ("Transitional",       ( 0.1,  0.3,  0.1), 1.35, 0.12),
]

PERTURBATIONS = ["NT", "RNF8-Ci", "MIS18A-Ci"]

# P(perturbation | state) — RNF8/MIS18A knockdown shifts cells towards the
# mesenchymal and transitional states, which is the qualitative shape of the
# published result this placeholder stands in for.
PERT_BY_STATE = [
    [0.55, 0.23, 0.22],   # Epithelial-like
    [0.22, 0.40, 0.38],   # Mesenchymal-like
    [0.42, 0.30, 0.28],   # Proliferative
    [0.48, 0.27, 0.25],   # Interferon-response
    [0.30, 0.36, 0.34],   # Stress / hypoxic
    [0.24, 0.39, 0.37],   # Transitional
]

PHASES = ["G1", "S", "G2M"]
PHASE_BY_STATE = [
    [0.62, 0.22, 0.16],
    [0.58, 0.24, 0.18],
    [0.28, 0.38, 0.34],   # Proliferative — cycling
    [0.68, 0.19, 0.13],
    [0.66, 0.20, 0.14],
    [0.55, 0.26, 0.19],
]


def pick(rng: random.Random, weights: list[float]) -> int:
    r = rng.random() * sum(weights)
    acc = 0.0
    for i, w in enumerate(weights):
        acc += w
        if r < acc:
            return i
    return len(weights) - 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", default="assets/data/embedding.json")
    ap.add_argument("--n", type=int, default=N)
    args = ap.parse_args()

    rng = random.Random(SEED)
    n = args.n

    state_weights = [s[3] for s in STATES]

    pc3d: list[float] = []
    umap: list[float] = []
    states: list[int] = []
    perts: list[int] = []
    phases: list[int] = []
    cv: list[float] = []

    for _ in range(n):
        si = pick(rng, state_weights)
        name, centre, spread, _w = STATES[si]

        # --- 3-D PC space: anisotropic Gaussian per state ---
        x = centre[0] + rng.gauss(0, spread)
        y = centre[1] + rng.gauss(0, spread * 0.85)
        z = centre[2] + rng.gauss(0, spread * 0.6)
        pc3d += [round(x, 3), round(y, 3), round(z, 3)]

        # --- UMAP: exaggerate between-cluster separation, tighten within ---
        ang = (si / len(STATES)) * math.tau + 0.35
        ux = math.cos(ang) * 7.4 + rng.gauss(0, spread * 0.85)
        uy = math.sin(ang) * 7.4 + rng.gauss(0, spread * 0.85)
        # A filament of transitional cells trailing towards the centre.
        if si == 5:
            t = rng.random()
            ux *= t * 0.85
            uy *= t * 0.85
        umap += [round(ux, 3), round(uy, 3)]

        pi = pick(rng, PERT_BY_STATE[si])
        states.append(si)
        perts.append(pi)
        phases.append(pick(rng, PHASE_BY_STATE[si]))

        # Heterogeneity rises under knockdown — the effect being illustrated.
        base = 0.34 + 0.10 * (si == 5) + 0.06 * (si == 1)
        bump = [0.0, 0.17, 0.21][pi]
        cv.append(round(max(0.0, rng.gauss(base + bump, 0.075)), 3))

    # PCA view = first two dimensions of the same 3-D cloud, so the hero's
    # collapse and the explorer's PCA tab are mutually consistent.
    pca = []
    for i in range(n):
        pca += [pc3d[i * 3], pc3d[i * 3 + 1]]

    payload = {
        "meta": {
            "n": n,
            "source": "SIMULATED — placeholder, not experimental data",
            "caption": (
                f"{n:,} simulated cells across six transcriptional states. "
                "This is synthetic placeholder data generated by "
                "tools/make_placeholder.py to demonstrate the viewer, not an "
                "experimental result. It will be replaced with a real "
                "Perturb-seq export. Colour by perturbation, cell-cycle phase, "
                "state, or transcriptional heterogeneity (CV); switch between "
                "the PCA and UMAP embeddings to morph between them."
            ),
            "heroCaption": f"{n:,} simulated cells · PCA → UMAP",
            "embeddingLabels": {"pca": "PCA", "umap": "UMAP"},
            "exportedBy": "tools/make_placeholder.py",
            "synthetic": True,
            "seed": SEED,
        },
        "coords": {"pca": pca, "umap": umap},
        "coords3d": pc3d,
        "labelSets": {
            "perturbation": {
                "label": "Perturbation",
                "levels": PERTURBATIONS,
                "values": perts,
            },
            "state": {
                "label": "Transcriptional state",
                "levels": [s[0] for s in STATES],
                "values": states,
            },
            "phase": {
                "label": "Cell-cycle phase",
                "levels": PHASES,
                "values": phases,
            },
        },
        "scores": {
            "heterogeneity_cv": {
                "label": "Heterogeneity (CV)",
                "range": [round(min(cv), 3), round(max(cv), 3)],
                "values": cv,
            },
        },
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as fh:
        json.dump(payload, fh, separators=(",", ":"))

    kb = round(os.path.getsize(args.output) / 1024)
    print(f"Wrote {args.output} ({kb} KB, {n} synthetic cells).")
    print("NOTE: synthetic. Replace with a real export before this matters.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
